name: CI/CD FastAPI Secure App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Ejecutar pruebas
        run: pytest -q --disable-warnings --maxfail=1

      - name: Auditoría de dependencias
        run: pip install pip-audit && pip-audit || true

      - name: Construir imagen Docker
        run: docker build -t fastapi-secure-app:latest .

      - name: Probar arranque de contenedor
        run: |
          docker run -d -p 8080:8000 fastapi-secure-app:latest
          sleep 10
          curl -f http://127.0.0.1:8080/health

      - name: Mostrar logs de contenedor
        run: docker ps && docker logs $(docker ps -q | head -n 1)
